### ISSUE TITLE
Current state is not updating properly in Insteon+

### ISSUE THREAD

**Issue by luisiam** [nfarina/homebridge-liftmaster#5]
The state is not updating in Insteon+ app. Sometimes it's stuck at opened. Sometimes it's stuck at closed.

**Comment by AppleTechy** [comment]
I currently have both Insteon+ and Apple's HM Catalog app on my phone. If I opened the Insteon+ app after starting home kit it showed both my Garage doors open but intact they were closed. I couldn't get it to pull the right state. I found that if I pulled the state of the garage door via Apple's home kit app and then went into the Insteon+ app it was successful at pulling the correct state. Though I haven't figured out if the issue belongs with Insteon+ app or if there is an issue with the plugin. I am leaning more on the side of Insteon+ not reading the data correctly/not asking for the correct data, as my HM catalog successfully pulls the correct state every time.

**Comment by luisiam** [comment]
That may be the issue with Insteon+ as the Elgato Eve app doesn't have that problem. However, that only happens on this plugins. There's no problem with the Nest and other light bulbs I have

**Comment by AppleTechy** [comment]
I haven't had an issue using insteon+ with any of my other plugins but thats not saying much because I have really only used Insteon+ to rename my devices.... I have been HM catalog for testing purposes to make sure everything is being connected to my HomeKit account. I intend on by Home for home kit app($15 USD) as it is suppose to be the best app but I don't want to invest that money until I completely get everything running smoothly which I can try and do with the free apps such as HM catalog, Elgato Eve, and Insteon+ or even Lutron's app. :)

**Comment by AppleTechy** [comment]
@luisiam I think I found the issue.... When you load homebridge it doesn't automatically refresh the state of the garage door. So what has happened is Insteon+ must not call for a refresh automatically when you open the app. When I use HM it calls the the update on the garage door state which then in turn Insteon+ picks up on then correcting the state of your garage door. Though HM has to manually call all of the data from HomeKit. I am not sure if this issue needs to be fixed with the Plugin or Insteon+ but I believe it is the plugin +as HM catalog doesn't seem to have an issue but it doesn't ca;; for the state id the first time I load the app. I have to manually ask it to call for the state data...  Is anyone else having this issue? Can anyone add a little code to the plugin to automatically call the state when it initializes the platform? @nfarina could you possible add the couple lines of code to the plugin and I think that might fix the issue but not an expert so I am not positive..

**Comment by luisiam** [comment]
HM catalog works the best for me so far.
Elgato Eve is super laggy for me even though I am on iPhone 6S Plus. It's worse on iPad. 
Insteon+ has problem with my garage door as mentioned and the scene implementation in the app is kinda weird.
Lutron is the worst. I am using caseta wireless so I have to use the app to setup light bulbs. It can only control HomeKit connected thermostats. The scene implementation is completely different from the HomeKit one. Totally not related

**Comment by AppleTechy** [comment]
@luisiam I have heard Home is the best app if your welling to pay for it.  I am planning on purchasing it as soon as I get all my home automation stuff integrated into HomeKit so I can use it as my daily driver for home automation stuff.
https://itunes.apple.com/us/app/home-smart-home-automation/id995994352?mt=8

**Comment by luisiam** [comment]
I hope that will be an easy fix =]

$15 is a bit too much for me. I will just use HM catalog as most of the time I just talk to Siri to control my stuff. I only do the config using the app.

**Comment by AppleTechy** [comment]
@luisiam Thats why I am holding off to buy it till I decide if HomeKit is worth the $15 for the solid app to use. I like HM because its pretty solid I just wish it had more functions because it can only read data it can't change any of it which is why I downloaded Insteon+ . :(

**Comment by luisiam** [comment]
I am able to rename my devices in HM

**Comment by AppleTechy** [comment]
@luisiam You can rename the Device name but not the Siri Name.Or at least I couldn't figure out how. I have 2 garage doors and the siri name for both of them was garage door though the device name was different. Therefore siri couldn't understand any commands relating to the garage door because she got confused to which garage door I was referring to. :/

**Comment by AppleTechy** [comment]
@luisiam Where you able to get it to update correctly?

**Comment by luisiam** [comment]
I can update without problem.
![capture](https://cloud.githubusercontent.com/assets/16310467/12220504/e3ea3f48-b729-11e5-9278-2f5ad3ea12a4.PNG)

**Comment by AppleTechy** [comment]
@luisiam I meant were u able to get insteon+ to successfully update the state of the garage door?

**Comment by luisiam** [comment]
Nope. Everything is still the same

**Comment by AppleTechy** [comment]
@luisiam are you on slack?

**Comment by AppleTechy** [comment]
@luisiam lets talk on slack will be easier to talk back and forth

**Comment by luisiam** [comment]
@AppleTechy Sure. My username in slack is the same

**Comment by danoday** [comment]
@AppleTechy - is there a Slack channel for homebridge-liftmaster?  If not, should one be added under the main Homebridge Slack team?

**Comment by AppleTechy** [comment]
@danoday there is now! :)

**Comment by AppleTechy** [comment]
So the decided problem is that Insteon+ and Elgato eve can send the command for the garage door to open/close but don't automatically refresh the state of the garage door so it doesn't think it has opened or closed the garage door as it hasn't read the response sent back. This problem of it not refreshing the state can be bypassed in Elgato eve by the user manually refreshing all state of every device. Though in insteon+ there is no force refresh button rendering it useless when dealing with garage doors. If you want to force refresh states of a specific garage door you can use Elgato eve or ask siri "Is the ____ Garage door open or closed?" Which causes an app wide refresh of the state. This query updates the state in Insteon+.

**Comment by AppleTechy** [comment]
issue #2
